### ISSUE TITLE
Crash after update to 58.21

### ISSUE THREAD

**Issue by Atrate** [Helium314/StreetComplete#605]
**How to Reproduce**
1. Update SCEE to 58.21 from previous version, try launching.
2. Crash.

**Versions affected**
58.21

**Logcat**
```
08-19 16:47:42.894  1696  1757 I ActivityTaskManager: Displayed de.westnordost.streetcomplete.expert/de.westnordost.streetcomplete.screens.MainActivity for user 0: +428ms
08-19 16:47:42.989 24740 24761 I Preloader: Loaded features dictionary in 0.4s
08-19 16:47:42.990 24740 24778 I Preloader: Preloading data took 0.4s
08-19 16:47:42.993 24740 24740 D Tangram : Loading native library took 0ms
08-19 16:47:42.995 24740 24740 D Tangram : MapController creation took 1ms
08-19 16:47:42.996 24740 24740 D Tangram : MapController init took 1ms
08-19 16:47:43.010 24740 24806 D Tangram : TANGRAM map.cpp:890: setup GL
08-19 16:47:43.014 24740 24740 E AndroidRuntime: FATAL EXCEPTION: main
08-19 16:47:43.014 24740 24740 E AndroidRuntime: Process: de.westnordost.streetcomplete.expert, PID: 24740
08-19 16:47:43.014 24740 24740 E AndroidRuntime: java.lang.IllegalArgumentException: No enum constant de.westnordost.streetcomplete.data.preferences.Theme.AUTO
08-19 16:47:43.014 24740 24740 E AndroidRuntime: 	at java.lang.Enum.valueOf(Enum.java:300)
08-19 16:47:43.014 24740 24740 E AndroidRuntime: 	at de.westnordost.streetcomplete.data.preferences.Theme.valueOf(Unknown Source:2)
08-19 16:47:43.014 24740 24740 E AndroidRuntime: 	at de.westnordost.streetcomplete.screens.main.map.components.SceneMapComponent.getSceneFilePath(SceneMapComponent.kt:95)
08-19 16:47:43.014 24740 24740 E AndroidRuntime: 	at de.westnordost.streetcomplete.screens.main.map.components.SceneMapComponent.loadScene(SceneMapComponent.kt:59)
08-19 16:47:43.014 24740 24740 E AndroidRuntime: 	at de.westnordost.streetcomplete.screens.main.map.MapFragment$onStart$1.invokeSuspend(MapFragment.kt:154)
08-19 16:47:43.014 24740 24740 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
08-19 16:47:43.014 24740 24740 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:252)
08-19 16:47:43.014 24740 24740 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:164)
08-19 16:47:43.014 24740 24740 E AndroidRuntime: 	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:466)
08-19 16:47:43.014 24740 24740 E AndroidRuntime: 	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:500)
08-19 16:47:43.014 24740 24740 E AndroidRuntime: 	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:489)
08-19 16:47:43.014 24740 24740 E AndroidRuntime: 	at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:587)
08-19 16:47:43.014 24740 24740 E AndroidRuntime: 	at kotlinx.coroutines.android.HandlerContext$scheduleResumeAfterDelay$$inlined$Runnable$1.run(Runnable.kt:15)
08-19 16:47:43.014 24740 24740 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:959)
08-19 16:47:43.014 24740 24740 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
08-19 16:47:43.014 24740 24740 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
08-19 16:47:43.014 24740 24740 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
08-19 16:47:43.014 24740 24740 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8592)
08-19 16:47:43.014 24740 24740 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-19 16:47:43.014 24740 24740 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
08-19 16:47:43.014 24740 24740 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
08-19 16:47:43.014 24740 24740 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@dd2c1c4, Dispatchers.Main.immediate]
08-19 16:47:43.016  1696 11287 W ActivityTaskManager:   Force finishing activity de.westnordost.streetcomplete.expert/de.westnordost.streetcomplete.screens.MainActivity
```

**Comment by FloEdelmann** [comment]
The `auto` theme option has been removed in upstream StreetComplete, so maybe this issue could also appear there?

**Comment by Helium314** [comment]
Possibly, if the user manually set the theme to auto and the auto theme was already removed a while ago. But in any case, the related code does not exist any more with the MapLibre switch, so this is already fixed.

**Comment by gorgobacka** [comment]
I'm experiencing the same issue (crashing app after launch) with the current version from F-Droid (58.21).

@Helium314 What does "this is already fixed" mean?
Do we have to wait for the next release or is there a workaround for the current release?

**Comment by cvzi** [comment]
@gorgobacka You can install the apk of the newest alpha version from Github: https://github.com/Helium314/SCEE/releases/tag/v59.0-alpha1 
That version fixed the problem for me.

**Comment by goldfndr** [comment]
It didn't fix it for me (59.0 alpha 1 also crashed), but perhaps it was due to a different cause. Ended up clearing data and restoring presets and overlays (but Other settings didn't restore — incompatible).

**Comment by Helium314** [comment]
> (but Other settings didn't restore — incompatible)

Can you clarify?
I had to export settings from 58.21 and import them even on a different phone (due to https://github.com/maplibre/maplibre-native/issues/2206) and it worked without any issues.

**Comment by goldfndr** [comment]
It was a settings file from 2024-03-28 during #594, so one of those versions.

**Comment by goldfndr** [comment]
er, make that #524, oof

**Comment by Helium314** [comment]
As far as I remember old settings files should not be a problem. What happens when you try to import the old settings?
