### ISSUE TITLE
Crossing markings quest adds check_date:check_date:crossing

### ISSUE THREAD

**Issue by ygra** [Helium314/StreetComplete#608]
**How to Reproduce**
Answer a crossing markings quest. In my case this was always answered with "no", but that is prpbably not relevant.

**Expected Behavior**
The tag being set should probably be just check_date:crossing.

**Does it happen in normal StreetComplete?**
No.

**Versions affected**
Android 11
SCEE 58.2

**Comment by rusty-snake** [comment]
https://github.com/Helium314/SCEE/issues/602

**Comment by mcliquid** [comment]
Overpass to check instances: https://overpass-turbo.eu/s/1Q53

**Comment by mnalis** [comment]
> Overpass to check instances: https://overpass-turbo.eu/s/1Q53

Those all seem from today.... I guess previous one were manually fixed by someone.

> @Helium314 Would it be good to release a ‘bug fix’ version? 

Yes, it would be good to have `58.22` released with a fix, as people are likely to stick to **last** pre-MapLibre version for several smaller releases until bugs from that big change are ironed out (and for comparison purposes too); so I'd definitely recommend that last non-MapLibre SCEE version should not produce incorrect data in the OSM database...

**Comment by mcliquid** [comment]
> Those all seem from today.... I guess previous one were manually fixed by someone.

Yes, that was me :)

Depending on the timeframe for a production release, a Bugfix version would be nice.

**Comment by Helium314** [comment]
duplicate of #602

**Comment by HolgerJeromin** [comment]
I added a comment on three changesets of three mappers which created the current 16 elements wïth this bug.

I checked that they did not used a newer scee version in the meantime but did not fixed the data in osm.

**Comment by mnalis** [comment]
> Depending on the timeframe for a production release, a Bugfix version would be nice.

[58.22](https://github.com/Helium314/SCEE/releases/tag/v58.22) (with a fix) has been released on GitHub!

@Helium314 I'm wondering whether we should blacklist affected versions (**after** `v58.22` hits the F-droid, of course)?

- pro: it would "encourage" upgrading to `58.22`; doing which will make sure that no new incorrect tags are generated (already queued incorrect tags would still get upload, but only this once [^1])

- con:  users might get confused/inconvenienced by _"need to upgrade"_ message


[^1]: it would not stop incorrect tags being added **immediately** since [#604](https://github.com/Helium314/SCEE/pull/604)  will only prevent new bugs from occurring AFAICT, and not fix [already queued incorrect tags](https://github.com/Helium314/SCEE/issues/602#issuecomment-2295302903)

**Comment by Helium314** [comment]
> @Helium314 I'm wondering whether we should blacklist affected versions (**after** `v58.22` hits the F-droid, of course)?

I hadn't thought of the blacklisting, thanks for reminding me! That should definitely be done.

**Comment by Helium314** [comment]
Though maybe you could do the blacklisting immediately...

**Comment by mnalis** [comment]
> I hadn't thought of the blacklisting, thanks for reminding me! That should definitely be done.

Sure @Helium314! 

However, unless you think there is great urgency, I'd rather do the blacklisting in a few days when fixed `v58.22` gets published on F-droid (in order to not confuse F-droid users with _"you must update SCEE now!"_ message, and then when they do try to update, F-droid telling them that no update exists :exploding_head:  )

I don't think that few days later would do much difference regarding cleanups...

---

Anyway, as far as I see bug is **only** in `v58.21` (even if this ticket mentions `v58.2` as affected version), right?

So, can you confirm the new line should be:

```
StreetComplete_ee 58.21         This version creates incorrect check_date:check_date:crossing tags. See issue #602
```

**Comment by Helium314** [comment]
Yes, looks good.
And it should only be in 58.21. Just checked and the fix was out before 59.0-alpha1
